[package]
name = "rs-chat"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8" # Web framework
serde = { version = "1.0", features = ["derive"] } # Serialization/deserialization
serde_json = "1.0" # Working with JSON
tokio = { version = "1", features = ["full"] } # Asynchronous runtime
tower = "0.5" # Middleware support
tower-http = { version = "0.6", features = ["trace"] } # HTTP utilities including TraceLayer
anyhow = "1.0" # Error handling
jsonwebtoken = {version = "11.0.0", features=["rust_crypto"]}
axum-extra = {version = "0.12.6", features = ["typed-header"]}
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
dotenvy = "0.15"
futures-util = "0.3"
chrono = "0.4"

[dependencies.mongodb]
version = "3.8.0"
